apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
    name: subdiretorio
    annotations:
      kubernetes.io/ingress.class: "traefik"
spec:
    rules:
    - http:
        paths:
        - path: /time
          backend:
            serviceName: time
            servicePort: 8080
        - path: /gateway
          backend:
            serviceName: gateway
            servicePort: 8080
