apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: subdominio
spec:
    rules:
    - host: blue.k8s-homelab.com.br
      http:
        paths:
        - backend:
            serviceName: blue-service
            servicePort: 80
    - host: green.k8s-homelab.com.br
      http:
        paths:
        - backend:
            serviceName: green-service
            servicePort: 80
