apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: subdominio
spec:
    rules:
    - host: blue.<DOMAIN-NAME>
      http:
        paths:
        - backend:
            serviceName: blue-service
            servicePort: 80
    - host: green.<DOMAIN-NAME>
      http:
        paths:
        - backend:
            serviceName: green-service
            servicePort: 80
