apiVersion: v1
kind: Service
metadata:
    name: blue-service
    annotations:
        dev.okteto.com/auto-ingress: "true"    
spec:
    selector:
        app: blue
    ports:
    - port: 80
      targetPort: 80